### ISSUE TITLE
Can't build with global giella-core

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-ceb#1]
With giella-core from packages, this language somehow still looks for a file in relative `../`? How is this language special?

`automake: error: cannot open < ../giella-core/am-shared/devtest-include.am: No such file or directory`

**Comment by snomos** [comment]
@flammie could you have a look?

**Comment by TinoDidriksen** [comment]
Nm, this was my mistake. Somehow, my giella-ceb files didn't list giella-core as a build-dep.

**Comment by TinoDidriksen** [comment]
...no, it does, just elsewhere.

**Comment by flammie** [comment]
well, if i remember correctly automake doesn't really support installed included files so the `autogen.sh` downloads `giella-core` to `$topsrcdir/../giella-core` anyways, and even that is a hack that shouldn't work but automake supports it for legacy reasons. There shouldn't be anything special with ceb in this respect, is it possible that there was a network error running autogen.sh, not sure if it returns fail exit codes?

**Comment by snomos** [comment]
I am pretty sure that `autogen.sh` does not return fail exit codes. We should probably add that for more robustness.

**Comment by TinoDidriksen** [comment]
Was still my fault, but in a completely different way. A handful of giella packages did not have their post-clone hooks updated, so they didn't get giella-core bundled.

(btw, the builders do not run autogen.sh and do not have network access)

**Comment by rueter** [comment]
My hunch is that problems with lang-ceb might be shared by lang-slh. Neither of these should have problems with post-clone hook updates, because they were both created after February 2024. 
Both languages also have fail the «Decision task».

**Comment by TinoDidriksen** [comment]
Different systems. My nightly builds have nothing to do with Divvun's Taskcluster builds, and don't show up on GitHub at all (yet).
